version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: task-manager-postgres
    environment:
      POSTGRES_DB: task_manager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task-manager-network

volumes:
  postgres_data:

networks:
  task-manager-network:
    driver: bridge
